// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.draka.hardi.domain;

import com.draka.hardi.domain.CustomerAudPK;
import java.io.Serializable;

privileged aspect CustomerAudPK_Roo_Serializable {
    
    declare parents: CustomerAudPK implements Serializable;
    
    private static final long CustomerAudPK.serialVersionUID = 1L;
    
}
