// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.draka.hardi.domain;

import com.draka.hardi.domain.PolicyTypeAudPK;
import java.io.Serializable;

privileged aspect PolicyTypeAudPK_Roo_Serializable {
    
    declare parents: PolicyTypeAudPK implements Serializable;
    
    private static final long PolicyTypeAudPK.serialVersionUID = 1L;
    
}
