// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.draka.hardi.domain;

import com.draka.hardi.domain.PolicyCustomerAudPK;
import java.io.Serializable;

privileged aspect PolicyCustomerAudPK_Roo_Serializable {
    
    declare parents: PolicyCustomerAudPK implements Serializable;
    
    private static final long PolicyCustomerAudPK.serialVersionUID = 1L;
    
}
