// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.draka.hardi.domain;

import com.draka.hardi.domain.Revisions;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Revisions_Roo_Configurable {
    
    declare @type: Revisions: @Configurable;
    
}
